In [1]:
import numpy as np

In [2]:
# Creating an array.
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# Accessing the elements of an array.
a = np.array([1, 2, 3, 4, 5])
a[0], a[1]

(1, 2)

In [4]:
#Indexing and slicing an array.
a[0:]

array([1, 2, 3, 4, 5])

In [5]:
a[0:3]

array([1, 2, 3])

In [7]:
a[:4]

array([1, 2, 3, 4])

In [8]:
a[2:]

array([3, 4, 5])

In [9]:
a[2:4]

array([3, 4])

In [11]:
a[[0, 2, -1]]# This is called multi-indexing. This creats another array.

array([1, 3, 5])

In [12]:
# Array types.
a.dtype

dtype('int32')

In [14]:
# Changing the array type.
np.array([1, 2, 3, 4, 5], dtype=np.float)

C:\Users\user\AppData\Local\Temp\ipykernel_11096\1349174260.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4, 5], dtype=np.float)


array([1., 2., 3., 4., 5.])

In [15]:
# Dimesions and shapes.
# This is a 2D array.
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A.shape

(2, 3)

In [16]:
A.ndim

2

In [17]:
A.size

6

In [28]:
# A 3D array
B = np.array([[
            [1, 2, 3],
            [4, 5, 6],
            [10, 11, 12],
        ],
        [
            [2, 3, 4],
            [1, 5, 2],
            [34, 25, 12],
        ]
])
B.shape

(2, 3, 3)

In [29]:
B.ndim

3

In [30]:
B.size

18

In [34]:
# Indexing and slicing multiple dimension arrays.
B[1]

array([[ 2,  3,  4],
       [ 1,  5,  2],
       [34, 25, 12]])

In [35]:
B[1, 0, 2]

4

In [36]:
B[0, :2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
B[1, 1:, 2:]

array([[ 2],
       [12]])

In [38]:
# Modifying an array.
B[1, 0] = np.array([34, 52, 89])

In [39]:
print(B)

[[[ 1  2  3]
  [ 4  5  6]
  [10 11 12]]

 [[34 52 89]
  [ 1  5  2]
  [34 25 12]]]


In [40]:
B[0, 1, 2] = 22
print(B)

[[[ 1  2  3]
  [ 4  5 22]
  [10 11 12]]

 [[34 52 89]
  [ 1  5  2]
  [34 25 12]]]


In [42]:
# Summary Statistics
B.sum()

324

In [43]:
B.mean()

18.0

In [44]:
B.std()

22.120880030716076