In [1]:
import numpy as np

In [4]:
# Numpy Array Creation
# Creates an array filled with zeros.
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Creates a 2*2 array filles with 1s
b = np.ones([2, 2], dtype=np.int8)
print(b)

[[1 1]
 [1 1]]


In [10]:
#Creates a 3*2 array filles with 4s.
c = np.ones([3, 2], dtype=np.int8) * 4
print(c)

[[4 4]
 [4 4]
 [4 4]]


In [14]:
# Creates an array with random integer values/uninitialized values.
d = np.empty(5, dtype=np.int8)
print(d)

[1 1 1 1 0]


In [18]:
# Creates an array of a constant value of specific data type.
e = np.full([3, 3], 12, dtype=np.int8)
print(e)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [19]:
# Creating an array that is evenly spaced.
f = np.arange(10)
print(f)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Creating an evenly spaced array ranging from 0 to 20.
g = np.arange(0, 20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
# Creating an evenly space array ranging from 0 to 1 with a spacing of 0.1
h = np.arange(0, 1, 0.1)
print(h)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [24]:
# Returning a sequence evenly spaced value in the range of 0 to 1
j = np.linspace(10, 20, 20)
print(j)

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


In [27]:
# Creating random arrays with random values.
k = np.random.random ([2, 2])
print(k)

[[0.46216896 0.33793957]
 [0.67281929 0.33870339]]


In [32]:
l = np.random.normal([2, 2])
print(l)

[1.79347586 2.3762937 ]


In [33]:
m = np.random.rand(2,4)
print(m)

[[0.45189023 0.69500462 0.03498133 0.9272561 ]
 [0.73085613 0.85773681 0.50086548 0.62030429]]


In [16]:
o = np.arange(8).reshape(2, 4)
print(o)

[[0 1 2 3]
 [4 5 6 7]]


In [15]:
p = np.arange(8).reshape(2, 2, 2)
print(p)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.eye(8, 8, k=-1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [21]:
np.eye(8, 8, k=-3, dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]], dtype=int8)