In [1]:
import numpy as np

In [2]:
# NUMPY OPERATIONS.
# Broadcasting and vectorized Operations.
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
# Vector operations between arrays and scalar
a + 10

array([10, 11, 12, 13])

In [5]:
a * 20

array([ 0, 20, 40, 60])

In [6]:
a / 2

array([0. , 0.5, 1. , 1.5])

In [10]:
# Vector operations between arrays and arrays.
# This works provided they are of the same size and shape.
b = np.arange(4, 8)

In [11]:
b

array([4, 5, 6, 7])

In [12]:
a + b

array([ 4,  6,  8, 10])

In [13]:
a * b

array([ 0,  5, 12, 21])

In [14]:
a - b

array([-4, -4, -4, -4])

In [15]:
b - a

array([4, 4, 4, 4])

In [16]:
a

array([0, 1, 2, 3])

In [17]:
b

array([4, 5, 6, 7])

In [18]:
# Modifying the array.
a += 20

In [19]:
a

array([20, 21, 22, 23])

In [20]:
# NUMPY BOOLEAN ARRAYS.
A = np.arange(10, 15)
A

array([10, 11, 12, 13, 14])

In [21]:
A[[0, -2]]

array([10, 13])

In [22]:
A[[True, False, False, True, False]]

array([10, 13])

In [28]:
A >= 12

array([False, False,  True,  True,  True])

In [29]:
A[A >= 12]

array([12, 13, 14])

In [34]:
A[(A == 10) | (A == 13)]

array([10, 13])

In [33]:
A

array([10, 11, 12, 13, 14])

In [35]:
A.mean()

12.0

In [36]:
A[A > A.mean()]

array([13, 14])

In [39]:
#NUMPY ALGEBRA AND SIZE
#Linear Algebra

i = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
j = np.array([
    [6, 5],
    [4, 3],
    [2, 1],
])

# Dot product.
i.dot(j)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [40]:
# Cross product
i @ j

array([[20, 14],
       [56, 41],
       [92, 68]])

In [41]:
i.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
j.T

array([[6, 4, 2],
       [5, 3, 1]])

In [43]:
i.T @ j.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [44]:
i.T @ j

array([[36, 24],
       [48, 33],
       [60, 42]])

In [45]:
j.T @ i

array([[36, 48, 60],
       [24, 33, 42]])